name: Build and Release

on:
  workflow_dispatch:
  
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build --progress plain -t my-image -f Dockerfile .

    - name: Extract API and DataTrainer artifacts
      run: |
        docker create --name my-container my-image
        docker cp my-container:/app/publish/API ./api-artifacts
        docker cp my-container:/app/publish/DataTrainer ./datatrainer-artifacts
        docker rm my-container

    - name: Archive API artifacts
      uses: actions/upload-artifact@v2
      with:
        name: api-artifacts
        path: ./api-artifacts

    - name: Archive DataTrainer artifacts
      uses: actions/upload-artifact@v2
      with:
        name: datatrainer-artifacts
        path: ./datatrainer-artifacts

    - name: Delete Docker image
      run: docker rmi my-image
